### ISSUE TITLE
Two parts of the interface appears to return different header values

### ISSUE THREAD

**Issue by peetera** [ChevronETC/TeaSeis.jl#21]
I was using TeaSeis in more elaborate ways than had before, and I ran into this unexpected behavior. 

Here is the code snippet:
```
using TeaSeis;
using PyPlot;
jsName = "/data/esdrd/akep/Julia/TeaSeisIssue/test.js"
YINDtest = 1400

io_H = jsopen(jsName, "r")
nFold = fold(io_H,YINDtest);

hdrs = readhdrs(io_H, :, :,  YINDtest);
cx1 = map(i->get(prop(io_H,"CDPX"), hdrs[:,i]),   1:nFold);
xi1 = map(i->get(prop(io_H,"XINDEX"), hdrs[:,i]), 1:nFold);

hdrs2 = readframehdrs(io_H,YINDtest)
cx2 = map(i->get(prop(io_H,"CDPX"), hdrs2[:,i]),   1:nFold);
xi2 = map(i->get(prop(io_H,"XINDEX"), hdrs2[:,i]), 1:nFold);

# ! method and/or using explicit loops produces same results
# hdrs3 = allocframehdrs(io_H);
# readframehdrs!(io_H, hdrs3, YINDtest)
# cx3 = Array{Float32,1}(undef,nFold)
# xi3 = Array{Int32,1}(undef,nFold)
# for i = 1:nFold
#     cx3[i] = get(prop(io_H,"CDPX"),   hdrs3[:,i]);
#     xi3[i] = get(prop(io_H,"XINDEX"), hdrs3[:,i]);
# end 

figure(1)
clf();
subplot(211) ; 
plot(cx1,       label="readhdrs"); 
plot(cx2, "--", label="readframehdrs"); 
# plot(cx3, "--", label="readframehdrs!");
legend() 
title("CDPX from headers"); xlabel("trace# from file"); ylabel("CDPX")
subplot(212) ; 
plot(xi1,       label="readhdrs")
plot(xi2, "--", label="readframehdrs" )
title("XINDEX from headers"); xlabel("trace# from file"); ylabel("XINDEX");
legend()
tight_layout()

println("Notice difference between readhdrs and readframehdrs!!!")
```
Here is the graph I see:
![TeaSeis_hdr_read_inconsistency](https://user-images.githubusercontent.com/32224687/77832565-205d9300-7105-11ea-8ae8-d81070b189be.png)

I believe the correct results are3 from `readframehdrs`.

**Comment by samtkaplan** [comment]
Thanks @peetera for the nice report.  However, this is actually intentional behavior.  What you are seeing is the automatic regularization of the data when the frames are not "full".  If you want equivalent results from the two methods, `readhdrs` and `readframehdrs`, then you will need to regularize what is returned from `readframehdrs`.

In particular, you would use the following line of code on `hdrs2`:
```
regularize!(io, hdrs2)
```
Or, we could add a method that would let you left justify `hdrs`:
```
leftjustify!(io, hdrs)
```
But (Whoops), `leftjustify!(io,hdrs)` does not exist in TeaSeis.jl.  It would be easy to add since its varient `leftjustify!(io,trcs,hdrs)` is implemented.  So, perhaps that is the first action that could be taken from this issue?  Let me know if that would be helpful.

The documentation [1] does mention that regularization is applied.  However, it doesn't explicitly mention the `regularize!` method for the headers-only use-case.  It does explicitly mention the `regularize!` method for the traced-and-headers use-case.  So, perhaps that is another action item to take from this issue.

Just to give some background on my thinking to regularize when using the `read`,`readtrcs`,`readhdrs` methods: I was thinking of these as methods that read a hyper-cube of data, rather than methods that read groups of frames.  Hence, the data in the hyper-cube should be placed in their regularized locations.  Otherwise, when one looks across the frame dimension, the data might not make sense.  I am happy to discuss this reasoning, and think of alternatives if it does not make sense.

Here's your plot with the `regularization` step added:

![Figure_1](https://user-images.githubusercontent.com/4575854/77837541-ef468800-712f-11ea-988a-e45048fbc0c9.png)

Thanks for using the package, and do not hesitate to ask follow-up questions (or request additional features)!

[1] https://github.com/ChevronETC/TeaSeis.jl#alternative-readwrite-methods-n-dimensional-slices

**Comment by peetera** [comment]
Thanks @samtkaplan. 
You are correct, if I plot the TRC_TYPE it also makes the issue evident, as seen below. 

What I thought was evidence against regularization being responsible, the apparently "valid" values of CDPX before the first live trace (trace# 785, yellow dashed curve), are in fact merely "undefined" by the standard as their `TRC_TYPE != 1` (red dotted curve)

![Closed_Issue](https://user-images.githubusercontent.com/32224687/78044764-b5959d00-733a-11ea-8637-cc62896ef925.png)
